import os

def generate_readme():
    """
    Generates a README.md file for the generated Terraform code.
    """
    output_dir = "generated_terraform"
    if not os.path.isdir(output_dir):
        print("Directory 'generated_terraform' not found. Nothing to do.")
        return

    readme_path = os.path.join(output_dir, "README.md")

    with open(readme_path, "w") as f:
        f.write("# Reverse Terraform GCP - Generated Infrastructure\n\n")
        f.write("This directory contains Terraform code that was automatically generated by the Reverse Terraform script.\n\n")

        f.write("## Summary of Discovered Resources\n\n")
        f.write("The following resource types were discovered and generated:\n\n")

        found_resources = False
        for item in os.listdir(output_dir):
            item_path = os.path.join(output_dir, item)
            if os.path.isdir(item_path):
                found_resources = True
                f.write(f"- **{item.capitalize()}**: Configuration in `{item}/{item}.tf` (or similar).\n")

        if not found_resources:
            f.write("No specific resource types were found in subdirectories.\n")

        f.write("\n## Next Steps\n\n")
        f.write("1. **Review the generated code**: Carefully inspect all `.tf` files to ensure they accurately represent your infrastructure.\n\n")
        f.write("2. **Initialize Terraform**:\n")
        f.write("   ```bash\n")
        f.write("   terraform init\n")
        f.write("   ```\n\n")
        f.write("3. **Run the Import Scripts**:\n")
        f.write("   If an `import.sh` script was generated (for the resource scraping method), you must run it to import your existing resources into the Terraform state.\n")
        f.write("   ```bash\n")
        f.write("   # Example for GCS buckets:\n")
        f.write("   sh gcs/import.sh\n")
        f.write("   ```\n\n")
        f.write("4. **Verify with `terraform plan`**:\n")
        f.write("   After importing, run `terraform plan`. It should show no changes, indicating that your state now matches your infrastructure.\n")
        f.write("   ```bash\n")
        f.write("   terraform plan\n")
        f.write("   ```\n\n")
        f.write("5. **Commit to version control**: Once you are satisfied, commit the generated code to your version control system.\n")

    print(f"Generated README.md in {readme_path}")

if __name__ == "__main__":
    generate_readme()
